spring:
  datasource:
    url: jdbc:h2:mem:moodtrip-test;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop   # 테스트마다 스키마 생성/삭제
    properties:
      hibernate:
        format_sql: true
        show_sql: false
  sql:
    init:
      mode: never

file:
  upload:
    path: ${java.io.tmpdir}/moodtrip-test-uploads

# 보안/웹이 올라와도 서비스 테스트엔 영향 없고, 필요시 로깅만 최소화
logging:
  level:
    org.hibernate.SQL: warn
    org.springframework.test: info